import Head from 'next/head'
import Nav from './Nav';
import Footer from './Footer';
import Header from './Header';
import layoutStyles from '../styles/Layout.module.css'

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Tourz Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<div className={layoutStyles.wrapper}>
				<Nav />
				<main className={layoutStyles.main}>
          <Header />
					{children}
				</main>
				<Footer />
			</div>
    </div>
	);
}


export default Layout;
