import Head from 'next/head'
import Nav from './Nav';
import Footer from './Footer';
import Header from './Header';
import styles from '../styles/layout.module.css'

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Tourz Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<div className={styles.container}>
				<Nav />
				<main className={styles.main}>
          <Header />
					{children}
				</main>
				<Footer />
			</div>
    </div>
	);
}


export default Layout;
