import Head from 'next/head'
import styles from '../styles/Layout.module.css'

const Layout = () => {
  return (
    <div>
      <Head>
        <title>Star News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<main>
				About page
			</main>
    </div>
	);
}

export default Layout;
