import Head from 'next/head'
import Image from 'next/image'

export default function About() {
  return (
    <div>
      <Head>
        <title>Tourz Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<main>
				About page
			</main>
    </div>
	);
}
