import Head from 'next/head'
import styles from '../styles/layout.module.css'
import ToursList from '../components/ToursList'

export default function Home({ tours }) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Tourz Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToursList tours={tours} />
      
    </div>
    
  )
}



// fetch on build time
export const getStaticProps = async() => {
  // const url1 = `https://jsonplaceholder.typicode.com/posts?_limit=6`;
  
  const url = `https://course-api.com/react-tours-project`;
  
  const res = await fetch(url);
  const tours = await res.json();

  return {
    props: {
      tours
    }
  }

}
