import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/layout.module.css'
import ToursList from '../components/ToursList'

export default function Home({ tours }) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Tourz Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToursList tours={tours} />
      
    </div>
  )
}




export const getStaticProps = async() => {

  const url = `https://course-api.com/react-tours-project`;

  const res = await fetch(url)

  return {
    props: {
      tours: await res.json(),
    }
  }
}


//{"id":"rec6d6T3q5EBIdCfD",
//"name":"Best of Paris in 7 Days Tour",
//"info":"Paris is synonymous with the finest things that culture can offer — in art, fashion, food, literature, and ideas. On this tour, your Paris-savvy Rick Steves guide will immerse you in the very best of the City of Light: the masterpiece-packed Louvre and Orsay museums, resilient Notre-Dame Cathedral, exquisite Sainte-Chapelle, and extravagant Palace of Versailles. You'll also enjoy guided neighborhood walks through the city's historic heart as well as quieter moments to slow down and savor the city's intimate cafés, colorful markets, and joie de vivre. Join us for the Best of Paris in 7 Days!",
//"image":"https://dl.airtable.com/.attachments/a0cd0702c443f31526267f38ea5314a1/2447eb7a/paris.jpg",
//"price":"1,995"}